export const types = {
    changeType: "[shape] Change Type",
    addShape: "[shape] Add Shape",
    shapeDrawing: "[shape] Shape Drawing",
    addCoordinate: "[coordinate] Add Coordinate",
    clearShapeDrawing: "[shape] Clear Shape Drawing",
    setActiveShape: "[shape] Set Active Shape",
    eraseShape: "[shape] Erase Shape",
    clearAction: "[shape] Clear Action",
    eraseSquare: "[erase] Square",
    eraseLine: "[erase] Line",
    eraseRightTriangle: "[erase] Right Triangle",
    eraseCircle: "[erase] Erase Circle",
    deleteShape: "[shape] Delete Shape",
    redraw: "[shape] Redraw shapes",
    changeColor: "[color] Change color",
    changeBorderColor: "[color] Change border color",
    changeFillColor: "[color] Change fill color",
    changeCoordinates: "[coordinates] Change Coordinates",
    movingShape: "[shape] Moving Shape",
    moveShape: "[shape] Move Shape",
    stopMoving: "[shape] Stop Moving",
    startMoving: "[shape] Start Moving",
    removeActiveShape: "[shape] Remove Active Shape",
    setACtiveShapeAfterInsert: "[shape] Set Active Shape After Insert",
    deletePositionShapes: "[shape] Dele Shape in array",
    movePosition: "[shape] Move Position",
    setSahpes: "[shape] Set Shapes",
    eraseAll: "[shape] Erase All"
}