export const types = {
    changeType: "[shape] Change Type",
    addShape: "[shape] Add Shape",
    shapeDrawing: "[shape] Shape Drawing",
    addCoordinate: "[coordinate] Add Coordinate",
    clearShapeDrawing: "[shape] Clear Shape Drawing",
    setActiveShape: "[shape] Set Active Shape",
    eraseShape: "[shape] Erase Shape",
    clearAction: "[shape] Clear Action",
    eraseSquare: "[erase] Square",
    eraseLine: "[erase] Line",
    deleteShape: "[shape] Delete Shape",
    redraw: "[shape] Redraw shapes",
    changeColor: "[color] Change color",
    changeBorderColor: "[color] Change border color",
    changeFillColor: "[color] Change fill color",
}